# Generated by Django 2.2.5 on 2019-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Cash', max_length=50),
            preserve_default=False,
        ),
    ]
