# Generated by Django 2.2.5 on 2019-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Descripcion de la pintura'),
            preserve_default=False,
        ),
    ]
